body:
  - type: input
    id: stream_id
    attributes:
      label: Stream ID (required)
      description: Unique ID of the channel and feed from [https://epgshare01.online/epgshare01/](https://epgshare01.online/epgshare01/). If you cannot find the channel or feed you are looking for in the list, please let us know via discord before posting your request.
      placeholder: 'BBC.America.HD.us2'
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: 'Any additional information that may help find a link to the stream faster?'

  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT:** Requests without a valid stream ID will be closed immediately.
